apiVersion: rbac.authorization.k8s.io/v1
kind: Role 
metadata:
  name: rates-deployment-manager 
  namespace: rates 
rules: 
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","list","watch","create","update","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rates-deployment-manager
  namespace: rates 
subjects:
- kind: ServiceAccount
  name: rates-sa 
  namespace: rates 
roleRef:
  kind: Role
  name: rates-deployment-manager
  apiGroup: rbac.authorization.k8s.io

